<?php

$reponame="sample_repo";
?>
<p>I won't be responsible if you download some malware from here and run it even if you aren't aware. [do NOT click on PHP files] <br/> Try scanning using <a href="https://virustotal.com">VirusTotal</a>.
<br/></p><!-- Import bootstrap-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<!--css-->

<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');
p,h1,h2,h4,h5,button,sub,a{font-family:"Roboto",sans-serif;color:white;font-size:16px;opacity: 0.75;}
h3{font-family:"Roboto",sans-serif;color:white;opacity:0.75;}
.sub {font-size:10px;opacity: 0.75;}
input,button{opacity: 0.75;}
body{background-color:#A9A9A9;); 
background-size: cover; }
input:focus{outline:black;outline-width:thick;transition-duration:2s;}
button:focus{outline:none;}
button{outline:none;}
*,button{border-radius:0px;outline:0;}
</style>
<!-- text -->
<h3>that cool file thing</h3>
<p></p>
<!-- upload form -->
<form action="upload.php" method="post" enctype="multipart/form-data" style="color:white;">
    <input type="file" name="fileToUpload" id="fileToUpload" style="background-color:white;color:grey;outline:none;border:none;">
    <input type="submit" value="Upload File" name="submit" style="background-color:white;color:grey;outline:none;border:none;" >
</form>

<br/><br/>
<!-- search form -->
<input type="textbox" id="search" placeholder="search.." style="background-color:white;color:grey;outline:none;border:none;"/>
<button type="button" onclick="window.open('/find.php?s=' + document.getElementById('search').value)" style="background-color:white;color:grey;outline:none;border:none;">search!</button>

<a href="/featured.php">featured files</a> 
<br/><hr/>
<h3>cool files people uploaded</h3>
<!-- files - generated by php code -->
<?php
$files=htmlspecialchars(shell_exec("ls contents"));
// echo "<!--Generated: No bugs in getting list of files.-->";
$files=explode("\n",$files);
// echo "<!--Generated: No bugs in converting list.-->";
function lm($filename) {

  return shell_exec("cd contents; stat -c %y ".escapeshellarg($filename)."; cd ..");
}
foreach ($files as &$file) {
  // echo "<!--Generated: loop reached ".$file."-->"
  if (file_exists("contents/".$file) and $file != "") {
    // echo $file;
    $template="<p class='bg-teal'><a href='/contents/%file%'>%file%</a> <span class='sub'>(last modified at %time% - %size% bytes)</span> %avlink%</p>";
    $template=str_replace("%file%",$file,$template);
    // $file=$file;
    $lstmdf=lm($file);
    // echo $lstmdf;
    $template=str_replace("%time%",$lstmdf,$template);
    $template=str_replace("%size%",htmlspecialchars(filesize("contents/".$file)),$template);
    $fileavlink="<a href='/check.php?file=".htmlspecialchars("contents/".$file)."'>Preview File</a>";
    $template=str_replace("%avlink%",$fileavlink,$template);
    echo $template;
  } else {
    ;
  }//USER=$(stat -c '%U' /path/to/your/file)
}